# Site settings
title: MEI Guidelines
email: info@music-encoding.org
baseurl: "/guidelines" 
url: "http://guidelines.music-encoding.org"
style_baseurl: "https://music-encoding.github.io"
#style_baseurl: "http://localhost:4001"
twitter_username: music-encoding
github: [metadata]


# Github repository used for Github edit button.
repository: "music-encoding/guidelines"

# path fragment to get to branch for files on github:
github_edit_path: "blob/master"

# Build settings
markdown: kramdown

exclude: [tools, dev]

plugins:
  - jekyll-redirect-from
  
menu:
    - id: versions
      label: 'Guidelines versions'
      url: ''
      submenu:
          - id: dev
            url: 'dev'
          - id: v3
            url: 'v3'

versions:
    dev: "development version"
    current: "v3"
    v3: "3.0.0"

collections:
  guidelines-v3:
    output: false

sidebar:  
    - id: s1
      content: 
          - id: guidelines
            label: 'Guidelines'
            url: 'content/'
          - id: elements
            label: 'Elements'
            url: 'elements.html'
          - id: attributeclasses
            label: 'Attribute Classes'
            url: 'attribute-classes.html'
          - id: modelclasses
            label: 'Model Classes'
            url: 'model-classes.html'
          - id: datatypes
            label: 'Data Types'
            url: 'data-types.html'